export const guitars = [
    {
        title: "ML-A4 BK",
        amount: 5,
        year: 2012,
        color: "чёрный",
        width: 52,
        type: "акустическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_8.jpg",
        id: 0,
        isChecked: false
    },
    {
        title: "ML-C1 WH",
        amount: 1,
        year: 2012,
        color: "белый",
        width: 45,
        type: "классическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_14.jpg",
        id: 1,
        isChecked: false
    },
    {
        title: "ML-C4 3/4 BK",
        amount: 2,
        year: 2022,
        color: "чёрный",
        width: 52,
        type: "классическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_12.jpg",
        id: 2,
        isChecked: false
    },
    {
        title: "ML-C5 PRO",
        amount: 6,
        year: 2017,
        color: "древесный",
        width: 52,
        type: "классическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_6.jpg",
        id: 3,
        isChecked: false
    },
    {
        title: "ML-D1 MAH/EQ",
        amount: 10,
        year: 2019,
        color: "древесный",
        width: 52,
        type: "акустическая",
        isPopular: 'да',
        image: "../components/assets/guitar_2.jpg",
        id: 4,
        isChecked: false
    },
    {
        title: "ML-D1 SP/EQ",
        amount: 10,
        year: 2020,
        color: "древесный",
        width: 45,
        type: "акустическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_9.jpg",
        id: 5,
        isChecked: false
    },
    {
        title: "ML-D1 SP/EQ",
        amount: 1,
        year: 2022,
        color: "древесный",
        width: 45,
        type: "электро-акустическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_11.jpg",
        id: 6,
        isChecked: false
    },
    {
        title: "ML-F3 AP/EQ",
        amount: 3,
        year: 2021,
        color: "древесный",
        width: 45,
        type: "акустическая",
        isPopular: 'да',
        image: "../components/assets/guitar_13.jpg",
        id: 7,
        isChecked: false
    },
    {
        title: "ML-F3 AP/EQ",
        amount: 5,
        year: 2014,
        color: "древесный",
        width: 45,
        type: 'электро-акустическая',
        isPopular: 'да',
        image: "../components/assets/guitar_1.jpg",
        id: 8,
        isChecked: false
    },
    {
        title: "ML-F3 PRO SLIM/EQ",
        amount: 11,
        year: 2018,
        color: "древесный",
        width: 52,
        type: "электро-акустическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_5.jpg", 
        id: 9,
        isChecked: false
    },
    {
        title: "ML-F3-BK",
        amount: 10,
        year: 2012,
        color: "чёрный",
        width: 45,
        type: "акустическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_3.jpg",
        id: 10,
        isChecked: false
    },
    {
        title: "ML-FINGERSTYLE",
        amount: 9,
        year: 2010,
        color: "древесный",
        width: 52,
        type: "акустическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_4.jpg",
        id: 11,
        isChecked: false
    },
    {
        title: "ML-FINGERSTYLE SP/EQ",
        amount: 10,
        year: 2020,
        color: "древесный",
        width: 52,
        type: "электро-акустическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_7.jpg",
        id: 12,
        isChecked: false
    },
    {
        title: "ML-FINGERSTYLE SP/EQ",
        amount: 11,
        year: 2018,
        color: "древесный",
        width: 45,
        type: "электро-акустическая",
        isPopular: 'нет',
        image: "../components/assets/guitar_10.jpg",
        id: 13,
        isChecked: false
    },
];